### ISSUE TITLE
Can‘t create SessionBuilder in class Websocket

### ISSUE THREAD

**Issue by nanomashinX** [wolfposd/TMChat#3]
Hello,
I need some help. I have made a jar using mvn package. When i start this jar using java -jar,  program will suspend at the following code and there is no any error messages. 

**this.wsSession = (new SessionBuilder()).......**

However it works well in  my IDE(idea) with debugger model. So what can i do for it?

**Comment by wolfposd** [comment]
make sure all the dependencies are included in the classpath and try the current version. i have updated some stuff in the websocket lib

**Comment by nanomashinX** [comment]
I bulide a jar file by using the packaging tool of idea instead of "mvn package". Then it starts successfully. But when i send messages from A to B, B can't receive the messages from A. The tendermint core has received the commit request. I can see the hash value. I start tendermint with "tendermint node --proxy_app=dummy". Thanks.

**Comment by wolfposd** [comment]
> "tendermint node --proxy_app=dummy"

start tendermint with "tendermint node"
TMChat is the app that connects to tendermint


1. run "tendermint node"
2. start TMChat
3. wait couple seconds for ABCI and websocket to connect
4. start sending messages
